// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDauWHi5LilaLyGKZ6FajTNkzvZfruYfgM',
    appId: '1:370941082115:android:86614dfa69f1090e77ec36',
    messagingSenderId: '370941082115',
    projectId: 'danrom-b0888',
    storageBucket: 'danrom-b0888.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnp4jkeBBV_xluCNIi5bkLb9IW1bl1K_A',
    appId: '1:370941082115:ios:87fc2585767ad29d77ec36',
    messagingSenderId: '370941082115',
    projectId: 'danrom-b0888',
    storageBucket: 'danrom-b0888.appspot.com',
    iosBundleId: 'com.example.danrom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnp4jkeBBV_xluCNIi5bkLb9IW1bl1K_A',
    appId: '1:370941082115:ios:87fc2585767ad29d77ec36',
    messagingSenderId: '370941082115',
    projectId: 'danrom-b0888',
    storageBucket: 'danrom-b0888.appspot.com',
    iosBundleId: 'com.example.danrom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkxLL7gA_rV6nCQN-TRvxSyNUS9B0PCRc',
    appId: '1:370941082115:web:e48639a886732fed77ec36',
    messagingSenderId: '370941082115',
    projectId: 'danrom-b0888',
    authDomain: 'danrom-b0888.firebaseapp.com',
    storageBucket: 'danrom-b0888.appspot.com',
    measurementId: 'G-424B6WEDTC',
  );
}
